# prepare（必须）:
#   1、程序运行前，首先需要初始化程序数据表
#   2、配置表结构转换规则，
#   - 优先级：表字段类型 > 库字段类型 两者都没配置默认采用内置转换规则
# reverse（必须）:
#   1、根据内置表结构转换规则或者手工配置表结构转换规则进行 schema 迁移
# all: TODO: 待测试
#   1、全量数据迁移
#   2、增量数据迁移
# full: TODO: 待测试断点续传
#   1、全量数据迁移 -> REPLACE INTO
[app]
# 事务 batch 数
# 用于数据写入 batch 提交事务数
insert-batch-size = 500
# 是否开启更新元数据库表慢日志,单位毫秒，默认 300ms
slowlog-threshold = 300

[reverse]
# 任务并发
reverse-threads = 8

[full]
# 按照表级别操作导出导入
# 任务 batch 数
# 1、用于判断每张表切分多少份
# 2、代表并发处理多少行数
worker-batch = 5
# 表导出导入并发数，同时处理多少张表
worker-threads = 3
# 单表 SQL 执行并发数
table-threads = 3
# 关于全量断点恢复
#   - 若想断点恢复，设置 enable-checkpoint true,首次一旦运行则 worker-batch 数不能调整，
#   - 若不想断点恢复或者重新调整 worker-batch 数，设置 enable-checkpoint false,重新运行全量任务
#   - 有可能无法断点续传，则需要设置  enable-checkpoint false 重新导入导出
enable-checkpoint = true

[all]
# 并发筛选 oracle 日志数
filter-threads = 16
# 并发表应用数，同时处理多少张表
apply-threads = 3
# apply-threads 每个表并发处理最大工作对列
worker-queue = 3
# apply-threads 每个表并发处理最大任务分发数
worker-threads = 3

[source]
# 源端 oracle 连接串
# 样例：用户名/密码@主机地址:数据库端口/实例名
dsn = "marvin/marvin@192.168.10.2:1521/orcl"
schema-name = "system"
# 源端迁移任务表
# include-table 和 exclude-table 不能同时配置，两者只能配置一个,如果两个都没配置则 Schema 内表全迁移
include-table = ["marvin1","marvin2","marvin3","test31"]
exclude-table = []

[target]
# 目标端 mysql 连接串
username = "marvin"
password = "marvin"
host = "192.168.2.90"
port = 5000
# 目标端元数据库
# CREATE DATABASE IF NOT EXIST dbsyncer_meta
meta-schema = "db_meta"
# 目标端导入 schema
schema-name = "steven"
# 对于现有的数据库特定行为（默认为 true）
# true 表示重命名然后创建
# false 表示跳过创建并打印警告记录
overwrite = true


[log]
# 日志 level
log-level = "info"
# 日志文件路径
log-file = "./transferdb.log"
# 每个日志文件保存的最大尺寸 单位：M
max-size = 128
# 文件最多保存多少天
max-days = 7
# 日志文件最多保存多少个备份
max-backups = 30