# prepare（必须）:
#   1、程序运行前，首先需要初始化程序数据表
#   2、配置表结构转换规则，
#   - 优先级：表字段类型 > 库字段类型 两者都没配置默认采用内置转换规则
# reverser（必须）:
#   1、根据内置表结构转换规则或者手工配置表结构转换规则进行 schema 迁移
[app]
# 任务并发
worker-threads = 8

[source]
# 源端 oracle 连接串
# 样例：用户名/密码@IP:端口/实例名
dsn = "system/marvin@192.168.0.125:1521/marvinpdb"
# 源端迁移 schema
schema-name = "system"
# 源端迁移任务表
# include-table 和 exclude-table 不能同时配置，两者只能配置一个,如果两个都没配置则全迁移
include-table = ["marvin1","marvin2","marvin3"]
exclude-table = []

[target]
# 目标端 mysql 连接串
username = "marvin"
password = "marvin"
host = "192.168.0.234"
port = 5000
# 目标端元数据库
# CREATE DATABASE IF NOT EXIST dbsyncer_meta
meta-schema = "db_meta"
# 目标端导入 schema
schema-name = "steven"
# 对于现有的数据库特定行为（默认为 true）
# true 表示重命名然后创建
# false 表示跳过创建并打印警告记录
overwrite = true


[log]
# 日志 level
log-level = "info"
# 日志文件路径
log-file = "./transferdb.log"
# 每个日志文件保存的最大尺寸 单位：M
max-size = 128
# 文件最多保存多少天
max-age = 7
# 日志文件最多保存多少个备份
max-backups = 30
# 是否压缩
compress = true