# prepare（必须）:
#   1、程序运行前，首先需要初始化程序数据表
#   2、配置 reverse 自定义转换规则
#   - 优先级：表字段类型 > 库字段类型 两者都没配置默认采用内置转换规则
# reverse:
#   1、prepare 前提必须阶段
#   2、根据内置表结构转换规则或者手工配置表结构转换规则进行 schema 迁移
# gather:
#   1、用于收集评估 oracle -> mysql/tidb 迁移成本信息，只适用于 schema 级别
# check:
#   1、表结构检查(独立于表结构转换，可单独运行，校验规则使用内置规则)
# all:（全量 + 增量模式）
#   1、全量数据迁移
#   2、增量数据迁移
# full: (全量模式)
#   1、全量数据迁移 -> REPLACE INTO
# csv：（全量模式）
#   1、全量数据导出 -> CSV
[app]
# 事务 batch 数
# 用于数据写入 batch 提交事务数
insert-batch-size = 500
# 是否开启更新元数据库表慢日志，单位毫秒
slowlog-threshold = 300
# 任务并发 -- 只用于 reverse/check 模式阶段
threads = 256
# pprof 端口
pprof-port = ":9696"
# http
http-port = "9000"
# JwtSecret string
jwt-secret = "666888"


[log]
# 日志 level
log-level = "info"
# 日志文件路径
log-file = "./conf/transferdb.log"
# 每个日志文件保存的最大尺寸 单位：M
max-size = 128
# 文件最多保存多少天
max-days = 7
# 日志文件最多保存多少个备份
max-backups = 30